In [2]:
import numpy as np

In [3]:
#1Create a NumPy array arr of integers from 0 to 5 and print its data type.
arr=np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [4]:
#2Given a NumPy array arr, check if its data type is float64
arr=np.array([0.1,0.2,0.3,0.4])
if arr.dtype == np.float64:
    print("Its float type of data")
else:
     print("its not an float64 type of data")


Its float type of data


In [5]:
#3Create a NumPy array arr with a data type of complex128 containing three complex numbers.
arr=np.array([1+2j,1+3j,1+4j],dtype=np.complex128)
print(arr)

[1.+2.j 1.+3.j 1.+4.j]


In [6]:
#4Convert an existing NumPy array arr of integers to float32 data type
arr=np.arange(12)
print(arr)
print(arr.dtype)
float_1 = arr.astype(np.float32)
print(float_1)
print(float_1.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
int64
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
float32


In [7]:
#5Given a NumPy array arr with float64 data type, convert it to float32 to reduce decimal precision.
arr=np.array([0.1,0.2,0.3,0.4])
print(arr)
print(arr.dtype)
float_32=arr.astype(np.float32)
print(float_32)
print(float_32.dtype)

[0.1 0.2 0.3 0.4]
float64
[0.1 0.2 0.3 0.4]
float32


In [8]:
#6Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type
def array_attributes(arr):
    shape= arr.shape
    size= arr.size
    dtype= arr.dtype
    return shape,size,dtype

arr=np.array([[0,1,2,3] ,[1,4,5,6]])
att=array_attributes(arr)
print("Shape",att[0])
print("Size",att[1])
print("Dtype",att[2])

Shape (2, 4)
Size 8
Dtype int64


In [9]:
#7 Create a function array_dimension that returns the dimensionality of a NumPy array.
def array_dimension(arr):
    dim=  arr.ndim
    return dim

arr=np.array([[1,2,3,4,5],[1,3,4,5,7],[1,321,452345,73437,535,]])
print(array_dimension(arr))

2


In [10]:
#8Design a function item_size_info that returns the item size and total size in bytesof a NumPy array.
def item_size_info(arr):
    item_size=arr.itemsize
    item_byte=arr.nbytes
    return item_size,item_byte

arr=np.array([[1,2,3,4],[11,22,33,44],[111,222,333,444]],dtype=np.int32)
item_size,item_byte=item_size_info(arr)
print("item size=",item_size)
print("item Byte=",item_byte)

item size= 4
item Byte= 48


In [11]:
#9Create a function array_strides that returns the strides of the given NumPy array.
def array_strides(arr):
    return arr.strides
arr=np.array([[1,2,3,4],[9,8,7,6],[11,12,13,14]])
print("Array",arr)
print("Strides",array_strides(arr))


Array [[ 1  2  3  4]
 [ 9  8  7  6]
 [11 12 13 14]]
Strides (32, 8)


In [12]:
#10Design a function shape_stride_relationship that returns the shape and strides of the given array
def shape_stride_relationship(arr):
    shape=arr.shape
    strides=arr.strides
    return shape,strides

arr=np.array([[1,2,3,4],[1,5,6,7]])
shape,strides=shape_stride_relationship(arr)
print("shape",shape)
print("strides",strides)

shape (2, 4)
strides (32, 8)


In [13]:
#11Create a function create_zeros_array(n) to return a NumPy array of zeros with n elements.
def create_zeros_array(shape):
    zeroes = np.zeros(shape)
    return zeroes

arr = np.array([[1, 2, 3], [1, 4, 5]])
print(create_zeros_array(arr.shape))

[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
#12Write a function create_ones_matrix(rows, cols) to create a 2D array filled with ones.
def create_ones_matrix(rows, cols):
    return np.ones((rows,cols))#2darray(()),3Darray((()))

matrix=create_ones_matrix(3,3)
print(matrix)
    

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
#13 Write a function generate_range_array(start, stop, step) to create a ranged NumPy array.
def generate_range_array(start, stop, step):
    return np.arange(start,stop,step)

arr=generate_range_array(0,12,1)
print(arr)
    

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [16]:
#14Design a function generate_linear_space(start, stop, num) for equally spaced values.
def generate_linear_space(start, stop, num):
    return np.linspace(start,stop,num)

arr=generate_linear_space(1,12,3)
print(arr)

[ 1.   6.5 12. ]


In [17]:
#15Create a function create_identity_matrix(n) using numpy.eye.
def create_identity_matrix(n):
    return np.eye(n)
arr=create_identity_matrix(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
#16Write a function that converts a Python list into a NumPy array
def convert_pylist_into_nparray(lst):
    return np.array(lst)
lst=[1,2,3,4,6,7,9]
con=convert_pylist_into_nparray(lst)
print(con)

[1 2 3 4 6 7 9]


In [19]:
#17Create a NumPy array and use numpy.view() to create a new view with the samedata.
arr=np.array([1,2,3,4,5,78,1])
print("old",arr)
new=arr.view()
print("new",new)
print("same data:",new.base is arr)

old [ 1  2  3  4  5 78  1]
new [ 1  2  3  4  5 78  1]
same data: True


In [20]:
#18Write a function to concatenate two NumPy arrays along a specified axis.
def concatenate(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
result=concatenate(a,b,axis=0)
print(result)
result1=concatenate(a,b,axis=1)
print(result1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [21]:
#19. Concatenate two arrays with different shapes horizontally using numpy.concatenate.
a = np.array([[1, 2,9], [3, 4,8]])
b = np.array([[5, 6], [7, 8]])
c=np.array([[5],[6]])
result=np.concatenate((a,b,c),axis=1)
print(result)

[[1 2 9 5 6 5]
 [3 4 8 7 8 6]]


In [22]:
#20Vertically stack multiple arrays from a list using numpy.vstack.
arr=[
    np.array([1,2,4]),
    np.array([2,3,4]),
    np.array([4,5,6])
]
result=np.vstack(arr)
print("Result:",result)

Result: [[1 2 4]
 [2 3 4]
 [4 5 6]]


In [23]:
#21Write a function to generate an array of integers within a specified range (inclusive) with a step.
def generate_int_range(start,stop,step):
    if step>0:
        stop+=1
    elif step<0:
        stop-=1
    return np.arange(start,stop,step,dtype=int)

arr=generate_int_range(1,10,2)
print(arr)
    

[1 3 5 7 9]


In [24]:
#22Generate 10 equally spaced values between 0 and 1 using NumPy.
space=np.linspace(0,1,10)
print(space)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [25]:
#23Create 5 logarithmically spaced values between 1 and 1000.
arr=np.logspace(0,3,num=5)
print(arr)

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [26]:
#24Create a Pandas DataFrame from a NumPy array with 5 rows and 3 columns of random integers (1-100).
import pandas as pd
arr = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(arr, columns=['maths', 'Science', 'S.st'])
print(df)

   maths  Science  S.st
0     77       24    69
1     27       43    86
2     97       56    53
3     35       54    74
4     73        4    38


In [27]:
#25. Write a function to replace all negative values in a specific column with zeros using NumPy
def replace_negatives_with_zero(arr, col):
    arr[:, col][arr[:, col] < 0] = 0
    return arr
a = np.array([[5, -3, 2],
              [-1, 4, -6],
              [7, -2, 9]])
#print(replace_negatives_with_zero(a,1))
print(replace_negatives_with_zero(a,0))
#print(replace_negatives_with_zero(a,2))

[[ 5 -3  2]
 [ 0  4 -6]
 [ 7 -2  9]]


In [28]:
#26Access the 3rd element from the given NumPy array
arr=np.array([1,2,4,5,6])
print(arr[2])

4


In [29]:
#27Retrieve the element at index (1, 2) from a 2D array.
arr=np.array([[1,2,4],
      [1,3,4]])
print(arr[1,2])

4


In [30]:
#28Extract elements greater than 5 using boolean indexing.
arr=np.array([[1,2,4],
              [1,3,9],
              [6,7,8]])
print(arr)
print("greater then 5:",arr[arr>5])

[[1 2 4]
 [1 3 9]
 [6 7 8]]
greater then 5: [9 6 7 8]


In [31]:
#29Slice elements from index 2 to 5 (inclusive) from a NumPy array.
arr=np.arange(15)
print(arr[2:5])

[2 3 4]


In [32]:
#30Slice the sub-array [[2, 3], [5, 6]] from a 2D array.
arr=np.array([[1,2,4],
              [1,3,9],
              [6,7,8]])
print(arr)
print("Sub-Array",arr[0:2])

[[1 2 4]
 [1 3 9]
 [6 7 8]]
Sub-Array [[1 2 4]
 [1 3 9]]


In [33]:
#31. Extract elements based on indices from a 2D array.
arr=np.array([[1,2,4],
              [1,3,9],
              [6,7,8]])
rows = [0, 1, 2]
cols = [1, 2, 0]
result=arr[rows,cols]
print("Extracted elements",result)


Extracted elements [2 9 6]


In [34]:
#32Filter elements greater than a threshold using boolean indexing.
arr=np.array([[1,2,4],[5,6,7],[1,2,4]])
threshold = 5
res=arr[arr>threshold]
print(arr)
print("elements greater then threshold",threshold ,":", res)

[[1 2 4]
 [5 6 7]
 [1 2 4]]
elements greater then threshold 5 : [6 7]


In [35]:
#33Extract specific elements from a 3D array using separate index arrays.
arr=np.array([[[1,2,3,4],
     [4,5,6,7],
    [6,7,8,9]],

     [[23, 24, 25, 26],
     [27, 28, 29, 30],
     [31, 32, 33, 34]]
    ])
i = np.array([0, 1, 1]) 
j = np.array([1, 0, 2])   
k = np.array([2, 3, 1]) 
result = arr[i, j, k]
print("Extracted elements:",result)

Extracted elements: [ 6 26 32]


In [36]:
#34Return elements satisfying two boolean conditions.
arr=np.array([1,2,4,5,7,8,9,18])
result=arr[(arr>10)&(arr%2==0)]
print(result)

[18]


In [37]:
#35Extract elements from a 2D array using separate row and column index arrays.
arr=np.array(
    [[1,2,4],
     [4,5,6],
     [1,5,7]])
rows=np.array([0,1,2])
cols=np.array([1,2,0])
result= arr[rows,cols]
print("Extracted elements:",result)

Extracted elements: [2 6 1]


In [40]:
#36 Add scalar 5 to every element of an array using broadcasting
arr=np.array(
    [[1,2,4],
     [4,5,6],
     [1,5,7]])
result=arr+5
print(result)

[[ 6  7  9]
 [ 9 10 11]
 [ 6 10 12]]


In [41]:
#37Multiply each row of a (3, 4) array by corresponding elements of a (1, 3) array
arr=np.array([[1,2,3,3],
              [1,3,4,5],
              [2,4,5,2]])
row=np.array([[2],
              [4],
              [3]])
res=arr*row
print(res)

[[ 2  4  6  6]
 [ 4 12 16 20]
 [ 6 12 15  6]]


In [43]:
#38. Add a (1, 4) array to every row of a (4, 3) array using broadcasting
arr=np.array([[1,2,3],
             [2,1,3],
             [1,1,3],
             [1,2,2]])
new=np.array([[1],
             [2],
             [3],
             [4]])
res=arr+new
print(res)

[[2 3 4]
 [4 3 5]
 [4 4 6]
 [5 6 6]]


In [46]:
#39Add two arrays of shapes (3, 1) and (1, 3) using broadcasting
arr=np.array([[1],
             [2],
             [3]])
new=np.array([[1,2,3]])
res=arr+new
print(res)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [49]:
#40Handle shape incompatibility during multiplication between (2, 3) and (2, 2) arrays
arr=np.array([[1,2],
             [2,3]])
new=np.array([[1,2,3],
             [1,1,1],
             ])
arr_expanded = np.concatenate([arr, np.ones((2,1))], axis=1) #add a column of ones
res=new*arr_expanded
print(res)

[[1. 4. 3.]
 [2. 3. 1.]]


In [52]:
#41Calculate column-wise mean of a 2D array
arr=np.array([[1,2,3],
             [1,1,1],
             [1,2,4]])
mean=arr.sum(axis=0)
print(mean)

[3 5 8]


In [55]:
#42Find maximum value in each row.
arr=np.array([[1,2,3],
             [2,3,4],
             [4,5,6]])
max_element=arr.max(axis=1)
print(max_element)

[3 4 6]


In [58]:
#43Find indices of maximum values in each column
arr=np.array([[1,2,3],
             [2,9,4],
             [4,5,6]])
max_indices=np.argmax(arr,axis=0)
print(max_indices)

[2 1 2]


In [60]:
#44Apply a custom function to compute moving sum along rows.
def moving_sum(row, window=2):
    return np.convolve(row, np.ones(window, dtype=int), 'valid')
arr=np.array([[1,2,3,1],
             [2,9,4,5],
             [4,5,6,4]])
res=np.apply_along_axis(moving_sum, axis=1, arr=arr)
print(res)

[[ 3  5  4]
 [11 13  9]
 [ 9 11 10]]


In [67]:
#45Check if all elements in each column are even
arr=np.array([[8,2,3,1],
             [2,3,4,16],
             [4,5,6,4]])
for col in range(arr.shape[1]):
    if np.all(arr[:, col] % 2 == 0):
        print(f"Column {col} → all even")
    else:
        print(f"Column {col} → not all even")

Column 0 → all even
Column 1 → not all even
Column 2 → not all even
Column 3 → not all even


In [70]:
#46Reshape a given array into dimensions m x n
arr=np.arange(12)
reshape=arr.reshape(3,4)
print("reshaped",reshape)

reshaped [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [71]:
#47Return a flattened version of a given matrix
arr=np.array([[8,2,3,1],
             [2,3,4,16],
             [4,5,6,4]])
flattened=arr.flatten()
print(flattened)

[ 8  2  3  1  2  3  4 16  4  5  6  4]


In [73]:
#48Concatenate two arrays along a specified axis
arr=np.array([[1,2,3],
             [2,3,1]])
arr2=np.array([[1,1,1],
              [1,2,3]])
res=np.concatenate((arr,arr2),axis=0)
print(res)

[[1 2 3]
 [2 3 1]
 [1 1 1]
 [1 2 3]]


In [86]:
 #49Split an array into sub-arrays along a specified axis.
arr=np.array([[1,2,2],
             [1,0,1],
             [1,2,2],
             [1,1,1]])
res=np.split(arr,2,axis=0)
for i,part in enumerate(res):
    print(f"part {i+1}:\n{part}")

part 1:
[[1 2 2]
 [1 0 1]]
part 2:
[[1 2 2]
 [1 1 1]]


In [91]:
#50. Insert and delete elements at specified indices from an array.
arr=np.array([[1,2,2],
             [1,0,1],
             [1,2,2],
             [1,1,1]])
new_arr=np.insert(arr,2,5)
print("After insertion",new_arr)
deleted_arr=np.delete(arr,3)
print("After deletion",deleted_arr)

After insertion [1 2 5 2 1 0 1 1 2 2 1 1 1]
After deletion [1 2 2 0 1 1 2 2 1 1 1]


In [94]:
#51Perform element-wise addition between two arrays
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])
res=a+b
print("Element-wise:",res)

Element-wise: [[ 6  8]
 [10 12]]


In [95]:
#52Perform element-wise subtraction: subtract arr2 from arr1.
arr1 = np.array([[10, 20],
                 [30, 40]])

arr2 = np.array([[1, 2],
                 [3, 4]])
res=arr1-arr2
print(result)

[[ 6  7  9]
 [ 9 10 11]
 [ 6 10 12]]


In [96]:
#53 Perform element-wise multiplication.
arr1 = np.array([[10, 20],
                 [30, 40]])

arr2 = np.array([[1, 2],
                 [3, 4]])
res=arr1*arr2
print("element-wise multiplication.",res)

element-wise multiplication. [[ 10  40]
 [ 90 160]]


In [99]:
#54Divide elements of arr1 by arr2 element-wise.
arr1 = np.array([[10, 20],
                 [30, 40]])

arr2 = np.array([[1, 2],
                 [3, 4]])
res=arr1/arr2
print(res)

[[10. 10.]
 [10. 10.]]


In [100]:
#55Perform element-wise exponentiation: arr1 ** arr2
arr1 = np.array([[10, 20],
                 [30, 40]])

arr2 = np.array([[1, 2],
                 [3, 4]])
res=arr1**arr2
print(res)

[[     10     400]
 [  27000 2560000]]


In [107]:
#56Count occurrences of a substring in a string array


arr = np.array(["apple", "pineapple", "grape", "apple pie", "banana"])
count = np.char.count(arr, "apple")
print("Occurrences of 'apple' in each element:", count)


Occurrences of 'apple' in each element: [1 1 0 1 0]


In [108]:
#57Extract uppercase characters from a string array.
arr = np.array(["Hello", "WORLD", "NumPy", "DATA", "science"])
uppercase_chars = [ ''.join([char for char in string if char.isupper()]) for string in arr ]
print("Uppercase characters:", uppercase_chars)

Uppercase characters: ['H', 'WORLD', 'NP', 'DATA', '']


In [109]:
#58Replace substring occurrences with another string in a string array.
arr = np.array(["data science", "big data", "data analysis"])
replaced_arr = np.char.replace(arr, "data", "info")
print(replaced_arr)

['info science' 'big info' 'info analysis']


In [110]:
#59Concatenate strings in a NumPy array element-wise.
arr1 = np.array(["Hello", "Good", "Data"])
arr2 = np.array(["World", "Morning", "Science"])
res=np.char.add(arr1,arr2)
print(res)

['HelloWorld' 'GoodMorning' 'DataScience']


In [111]:
#60 Find the length of the longest string in a string array
arr = np.array(["AI", "Machine Learning", "Data", "Neural Networks"])
lengths = np.char.str_len(arr)
max_length = np.max(lengths)
print("Length of the longest string:", max_length)

Length of the longest string: 16


In [112]:
#61Generate 100 random integers (1–1000) and compute mean, median, variance, and std deviation.
data = np.random.randint(1, 1001, size=100)
mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_dev = np.std(data)

# Display results
print("Data:", data)
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_dev)

Data: [574 851 843 561 832 420 911 231 407 437 117 399 584 787 700 117 607 495
 214 544 179 845 587 401 716 369 435 267 278 937 873 940 563 717 841 701
 799 261 742 701 141 215 304 364 417 280 550  84 567 759 630  11 254 859
 943 344 302 267  28 461 349 741 358  78 998 756 169 783 930  23 908  51
 424 471 549 247 238 869 413 203 204 539 799 832  75 857 392 384 232   1
 761 859 486 666 681 720 922 852 842 303]
Mean: 515.28
Median: 517.0
Variance: 77095.2416
Standard Deviation: 277.660298926584


In [113]:
#62Generate 50 random numbers (1–100) and compute the 25th and 75th percentiles.
data = np.random.randint(1, 101, size=50)
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)
print("Data:", data)
print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)

Data: [26 43 90 29 70 12 61 26 45 60 74 83 20 76 96 23 67  8 96 29 37 70 63 89
 11 65 34 21  3 96 54  9 30  5 24 95 76 52 62 40 76 73 47 23 80 15 30 69
 57 18]
25th Percentile: 24.5
75th Percentile: 72.25


In [114]:
#. 63Compute correlation coefficient between two arrays using np.corrcoef.
x = np.array([10, 20, 30, 40, 50])
y = np.array([12, 24, 33, 47, 55])
corr_matrix = np.corrcoef(x, y)
corr_coef = corr_matrix[0, 1]
print("matrix",corr_matrix)
print("correlation",corr_coef)

matrix [[1.         0.99719224]
 [0.99719224 1.        ]]
correlation 0.9971922417083551


In [115]:
#64. Perform matrix multiplication using np.dot
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])
result = np.dot(A, B)
print(result)

[[19 22]
 [43 50]]


In [116]:
#65. Compute the 10th, 50th, and 90th percentiles and quartiles for an array of 50 integers
data = np.random.randint(1, 101, size=50)
p10 = np.percentile(data, 10)
p50 = np.percentile(data, 50) 
p90 = np.percentile(data, 90)

q1 = np.percentile(data, 25)
q2 = np.percentile(data, 50)
q3 = np.percentile(data, 75)

print("Data:", data)
print("\nPercentiles:")
print("10th Percentile:", p10)
print("50th Percentile (Median):", p50)
print("90th Percentile:", p90)

print("\nQuartiles:")
print("Q1 (25%):", q1)
print("Q2 (Median):", q2)
print("Q3 (75%):", q3)


Data: [ 95  64  66  25  15  22  31  20  92  40  67  88  40  10  31  90  12  27
  24  41  44   8  62  86  30  18  95  72  83  72  15  40  27  31  39  62
  64  67  67 100  13  52  75  27  60   8   7  89  78  53]

Percentiles:
10th Percentile: 12.9
50th Percentile (Median): 42.5
90th Percentile: 89.1

Quartiles:
Q1 (25%): 25.5
Q2 (Median): 42.5
Q3 (75%): 70.75


In [117]:
#66. Find index of a specific element in an array
arr = np.array([10, 20, 30, 40, 50])
index = np.where(arr == 30)
print("Index of 30:", index[0])


Index of 30: [2]


In [119]:
#67. Sort a random array in ascending order.
arr = np.random.randint(1, 101, size=10)
sorted_arr = np.sort(arr)
print("Original array:", arr)
print("Sorted array:", sorted_arr)

Original array: [ 1 58 74 17  5 52 35  7 98 32]
Sorted array: [ 1  5  7 17 32 35 52 58 74 98]


In [120]:
#68. Filter elements greater than 20.
arr = np.array([5, 12, 25, 40, 18, 33, 7])
filtered=arr[arr>20]
print(filtered)

[25 40 33]


In [125]:
#69. Filter elements divisible by 3.
arr = np.array([5, 12, 25, 40, 18, 33, 7])
filtered=arr[arr%3==0]
print(filtered)

[12 18 33]


In [127]:
#70. Filter elements between 20 and 40 (inclusive). 
arr = np.array([5, 12, 25, 40, 18, 33, 7])
filtered = arr[(arr >= 20) & (arr <= 40)]
print(filtered)

[25 40 33]


In [128]:
#71. Check byte order of a NumPy array using dtype.byteorder.
arr = np.array([1, 2, 3], dtype=np.int32)
byte_order = arr.dtype.byteorder
print("Byte order:", byte_order)

Byte order: =


In [129]:
#72. Perform in-place byte swapping using byteswap().
arr = np.array([1, 256, 4096], dtype=np.int16)
print("Original array:", arr)
arr.byteswap(inplace=True)
print("After in-place byte swap:", arr)

Original array: [   1  256 4096]
After in-place byte swap: [256   1  16]
